### ISSUE TITLE
Setting the git tag: v1.1.1

### ISSUE THREAD

**Issue by junaruga** [steveklabnik/mono_logger#11]
Thanks for the new version 1.1.1's release. Could you set the `v1.1.1` tag to this repository?

https://rubygems.org/gems/mono_logger/versions/1.1.1

Here is the current tags.

```
$ git tag -n
v1.0.0          Version 1.0.0
v1.0.1          Version 1.0.1
v1.1.0          Version 1.1.0
```

Thanks.

**Comment by junaruga** [comment]
@steveklabnik For your comment on https://github.com/steveklabnik/mono_logger/issues/9#issuecomment-806054230, congrats and thanks for that! I think you forget to do `git tag` for this repository.

**Comment by steveklabnik** [comment]
I thought that rake release pushed tags; I guess it didn't. One moment...

**Comment by steveklabnik** [comment]
https://github.com/steveklabnik/mono_logger/releases/tag/v1.1.1

thank you!
